CREATE TABLE DIRECTOR(
DirectorID DECIMAL(2,0),
DirectorLast CHAR(12),
DirectorMiddle Char(10),
DirectorFirst CHAR(10),
CONSTRAINT		DIRECTOR_PK		PRIMARY KEY(DirectorID)
);

CREATE TABLE COMPANY(
CompanyID DECIMAL(2,0),
CompanyName CHAR(50),
CompanyAddress Char(50),
CONSTRAINT		COMPANY_PK		PRIMARY KEY(CompanyID)
);

CREATE TABLE GENRE(
GenreID DECIMAL(3,0),
GenreTitle CHAR(10)
CONSTRAINT		GENRE_PK		PRIMARY KEY(GenreID)
);

CREATE TABLE ACTOR(
ActorID DECIMAL(4,0),
ActorLast CHAR(12),
ActorMiddle CHAR(10),
ActorFirst CHAR(10),
CONSTRAINT		ACTOR_PK		PRIMARY KEY(ActorID)
);

CREATE TABLE MOVIE(
MovieID DECIMAL(3,0),
MovieName CHAR(50),
YearMade DECIMAL(4,0),
GenreID DECIMAL(3,0),
CONSTRAINT		MOVIE_PK		PRIMARY KEY(MovieID),

CONSTRAINT		MOVIE_FK	 FOREIGN KEY(GenreID)
							REFERENCES GENRE(GenreID)
								ON UPDATE NO ACTION
								ON DELETE NO ACTION
);

CREATE TABLE MOVIE_COMPANY(
MovieID DECIMAL(3,0),
CompanyID DECIMAL(2,0),
CONSTRAINT		MOVIE_CO_PK		PRIMARY KEY(MovieID, CompanyID),

CONSTRAINT		MOVIE_CO_MV_FK		 FOREIGN KEY(MovieID)
									REFERENCES MOVIE(MovieID)
										ON UPDATE NO ACTION
										ON DELETE NO ACTION,
	CONSTRAINT		MOVIE_CO_CO_FK		 FOREIGN KEY(CompanyID)
									REFERENCES COMPANY(CompanyID)
										ON UPDATE CASCADE
										ON DELETE NO ACTION
);

CREATE TABLE MOVIE_DIRECTOR(
MovieID DECIMAL(3,0),
DirectorID DECIMAL(2,0),
CONSTRAINT		MOVIE_DIR_PK		PRIMARY KEY(MovieID, DirectorID),

CONSTRAINT		MOVIE_DIR_MV_FK		 FOREIGN KEY(MovieID)
									REFERENCES MOVIE(MovieID)
										ON UPDATE NO ACTION
										ON DELETE NO ACTION,
	CONSTRAINT		MOCIE_DIR_CO_FK		 FOREIGN KEY(DirectorID)
									REFERENCES DIRECTOR(DirectorID)
										ON UPDATE CASCADE
										ON DELETE NO ACTION
);

CREATE TABLE REMAKE(
MovieID DECIMAL(3,0),
MovieIDRemake DECIMAL(3,0),
CONSTRAINT		REMAKE_PK		PRIMARY KEY(MovieID),

CONSTRAINT		REMAKE_MV_FK		 FOREIGN KEY(MovieID)
									REFERENCES MOVIE(MovieID)
										ON UPDATE NO ACTION
										ON DELETE NO ACTION
);

CREATE TABLE CHARACTER(
CharacterID DECIMAL(3,0),
MovieID DECIMAL(3,0),
CharacterName CHAR(12),
CharacterRole CHAR(10),
ActorID DECIMAL(4,0),
CONSTRAINT		CHARACTER_PK		PRIMARY KEY(CharacterID),

CONSTRAINT		CHARACTER_MV_FK		 FOREIGN KEY(MovieID)
									REFERENCES MOVIE(MovieID)
										ON UPDATE NO ACTION
										ON DELETE NO ACTION,
	CONSTRAINT		CHARACTER_ACT_FK		 FOREIGN KEY(ActorID)
									REFERENCES ACTOR(ActorID)
										ON UPDATE CASCADE
										ON DELETE NO ACTION
);

CREATE TABLE MOVIE_QUOTE(
MQID DECIMAL(2,0),
MovieID DECIMAL(3,0),
CharacterID DECIMAL(3,0),
MQ_Text Char(100),
CONSTRAINT		MOVIE_QT_PK		PRIMARY KEY(MQID),

CONSTRAINT		MOVIE_QT_MV_FK		 FOREIGN KEY(MovieID)
									REFERENCES MOVIE(MovieID)
										ON UPDATE NO ACTION
										ON DELETE NO ACTION,
	CONSTRAINT		MOVIE_QT_CHAR_FK		 FOREIGN KEY(CharacterID)
									REFERENCES CHARACTER(CharacterID)
										ON UPDATE CASCADE
										ON DELETE NO ACTION
);